# Generated by Django 4.2 on 2026-03-19 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_animal_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='popular_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='popular_lines', to='main_app.animal'),
        ),
    ]
