# Generated by Django 4.2 on 2026-03-30 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_animal_popular_line'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ('-id',)},
        ),
        migrations.CreateModel(
            name='MeasurementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='measurements')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main_app.measurement')),
            ],
        ),
    ]
