# Generated by Django 4.2 on 2026-04-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_animal_options_measurementfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
